language: node_js
node_js:
- '0.11'
before_install:
- cp scripts/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- cp scripts/cfindex.sh $HOME/
- chmod +x $HOME/cfindex.sh
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
- cd built
after_deploy:
- $HOME/travis-ci.sh after-deploy
deploy:
- provider: releases
  api_key:
    secure: PHYaRPogtbjY8y5eoEJLPZzrEuGZ4yDsVlrF0jhiZmWpTdxWIEJOZf0peixvNGE9erBzNfQAn0Ubh2JZXB6lYKaDVua7XsPFfEOJPrlY+f14o6m5kC9O7yRlPY6ezEZbZjCGq86A0/l6uaHLScyCCvodeSZReDP+7xJXQHuEkJw=
  file:
  - kalabox-win-$TRAVIS_TAG.zip
  - kalabox-osx-$TRAVIS_TAG.tar.gz
  - kalabox-linux32-$TRAVIS_TAG.tar.gz
  - kalabox-linux64-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: kalabox/kalabox
    all_branches: true
    tags: true
- provider: cloudfiles
  username: kalamuna
  api_key:
    secure: kZ1n6iNPWbs9ENeH4bJoEwKoJ0jn/V1tY+BwNXMeVsf86theVeePZTqRKaAz76IpHVRwZnFVPbzjzdYKEm8Qnz45rUnfwyBDsn+/RC/76i09AnZ/oeX+21h9IoabA5N7cMg4Gu10eFmjQDvJKm8z1v+jZB6A1tP1sXyi+Q2xazQ=
  region: ord
  container: kb2
  skip_cleanup: true
  on:
    repo: kalabox/kalabox
    branch: master
cache:
  directories:
  - node_modules
notifications:
  slack:
    rooms:
    - kalamuna:dP7cYTtQ5mOBCp9cpyHHnUYN#kalabox
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalamuna.com
    - alec@kalamuna.com
    - coder1@gmail.com
    on_success: always
env:
  global:
    secure: Zx94toqGScUIRZ/LBx0h8L/y/Lff4YFV+5QMbec+73ZpQMlATLqa4bl0PFy9Cp2RNNN9ljqkMoUQLanBetaPdL3Wxqo6qUloCrnPN/mzIVrL/mbbmG7bz6dVjtcB3CmheYTmdSBjNv+5n/gtb6DWfuX5Pdd9gVxruRqwHT3tW3g=
